# Site settings
title: American Gutters - Professional Gutter Installation
email: info@americanremodeling.net
description: >-
  Professional gutter installation and repair services. Protect your home with quality gutters installed by experts.
baseurl: "/gutter-leads" # the subpath of your site
url: "https://tim-amredev.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Default layout
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github

